#!/bin/bash
# tests/provenance.sh — bin/fleet provenance one-command audit receipt.
#
# Ticket 0029. One assertion block per acceptance-criteria checkbox in
# docs/backlog/0029-fleet-provenance-pr-forensics.md:
#
#   AC#1  default invocation (no flags) → --format text, exit 0,
#         keys in fixed order, byte-matches the text golden.
#   AC#2  --format md emits the same fields under a `# Provenance` H1
#         and ends with a `<!-- generated by fleet provenance -->` marker;
#         byte-exact against the md golden.
#   AC#3  --format json emits one parseable JSON object with the snake_cased
#         keys in the documented set. Parses via node.
#   AC#4  prompts SHA: drift wins when a prompts_drift event fired before
#         the pr_opened event; manifest's PROMPTS_SHA otherwise (read via
#         `git show <merge>:agents.config.sh` through the stub).
#   AC#5  prompts version: --changelog entry whose YYYY-MM-DD precedes the
#         merge ts. Tested in both branches (entry found / no entry).
#   AC#6  heal attempts: count of commit subjects beginning with `heal:` on
#         the merge SHA's branch range. Capped at 2.
#   AC#7  infra-flake reruns: count of infra_flake_rerun events whose pr=
#         matches and whose ts is between pr_opened and merge. The
#         pattern is listed parenthetically.
#   AC#8  review verdict: --request-changes when a lesson_draft_emitted
#         event with pr=<n> exists; --comment otherwise. No `gh api`.
#   AC#9  cross-fleet lessons at PHASE 0: count of `^### ` lines in
#         CROSS_LESSONS.md at the merge ts (via the synthetic git replay).
#   AC#10 spend: digest_spend_since restricted to [pr_opened.ts, merged.ts].
#   AC#11 unknown PR → stderr "provenance: PR #<n> not found in events.jsonl
#         for <slug> (no pr_opened or run_completed event matched)" + exit 2.
#   AC#12 unknown slug → stderr "provenance: no project with SLUG=<slug>
#         found (looked under FLEET_DISCOVERY_ROOT=<path>)" + exit 2.
#   AC#13 --help banner mentions --format, --help, three format values,
#         and one example. Assert via grep -qF -- "$kw" per LESSONS
#         2026-05-30. Function ends with explicit `exit 0` per LESSONS
#         2026-06-01 (dispatcher fall-through trap).
#
# Per LESSONS 2026-05-26 stubs live in $HOME/.local/bin so they survive
# lib/common.sh's PATH reset. Per LESSONS 2026-05-27 we use `cp` for
# fixture copies — never `$(cat …)` round-trips.

set -euo pipefail

REPO_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"
FLEET="$REPO_ROOT/bin/fleet"
FIXTURES="$REPO_ROOT/tests/fixtures/provenance"
GOLDEN_TEXT="$FIXTURES/provenance.text.golden.txt"
GOLDEN_MD="$FIXTURES/provenance.md.golden.txt"
GOLDEN_JSON="$FIXTURES/provenance.json.golden.txt"

TMP="$(mktemp -d -t fleet-provenance-test.XXXXXX)"
trap 'rm -rf "$TMP"' EXIT

# Isolate HOME so the per-slug cache resolves under $TMP and the test
# never reads from / writes to the host's real ~/.cache. Per LESSONS
# 2026-05-26, stubs go under $HOME/.local/bin (PATH-reset survivors).
export HOME="$TMP/home"
mkdir -p "$HOME/.local/bin"

# --- Stubs: gh fails on invoke; git is a deterministic replay --------------
# The command MUST resolve every field reading only local channel files
# (events.jsonl, runs.jsonl) and the synthetic git replay dir. A `gh api`
# call breaks the test — per AC#8 "the events channel is the source of
# truth per P-6".
cat > "$HOME/.local/bin/gh" <<'STUB'
#!/bin/bash
echo "gh stub: provenance MUST NOT call gh (got: $*)" >&2
exit 99
STUB
chmod +x "$HOME/.local/bin/gh"

# git stub: dispatch the two shapes the implementation needs to read from
# replay-dir-shaped data. Pulls $FLEET_GIT_REPLAY_DIR from env.
#
#   git show <sha>:<path>                  → cat $REPLAY/show/<sha>--<basename>
#   git log --format=%s <base>..<sha>      → cat $REPLAY/log/<sha>.subjects.txt
#   git log -1 --until=<ts> --format=%H -- CROSS_LESSONS.md
#                                          → cat $REPLAY/cross-lessons-sha.txt
#
# Any other invocation exits non-zero so a stray git call surfaces in the
# implementation rather than silently returning empty.
cat > "$HOME/.local/bin/git" <<'STUB'
#!/bin/bash
REPLAY="${FLEET_GIT_REPLAY_DIR:-}"
if [ -z "$REPLAY" ] || [ ! -d "$REPLAY" ]; then
  echo "git stub: FLEET_GIT_REPLAY_DIR unset or missing (got: $*)" >&2
  exit 99
fi
# git show <sha>:<path>
if [ "$1" = "show" ] && [[ "$2" == *:* ]]; then
  sha="${2%%:*}"
  spec="${2#*:}"
  base="$(basename "$spec")"
  f="$REPLAY/show/${sha}--${base}"
  if [ -f "$f" ]; then cat "$f"; exit 0; fi
  echo "git stub: no replay for show $sha:$spec at $f" >&2
  exit 1
fi
# git log -1 --until=<ts> --format=%H -- CROSS_LESSONS.md
if [ "$1" = "log" ]; then
  # Detect the CROSS_LESSONS.md lookup variant.
  for arg in "$@"; do
    if [ "$arg" = "CROSS_LESSONS.md" ]; then
      if [ -f "$REPLAY/cross-lessons-sha.txt" ]; then
        cat "$REPLAY/cross-lessons-sha.txt"
        exit 0
      fi
      exit 1
    fi
  done
  # Otherwise: git log --format=%s <base>..<sha>
  # Find the last positional that looks like base..sha; the sha is the
  # suffix after the literal ".." pair.
  for arg in "$@"; do
    case "$arg" in
      *..*)
        sha="${arg##*..}"
        f="$REPLAY/log/${sha}.subjects.txt"
        if [ -f "$f" ]; then cat "$f"; exit 0; fi
        echo "git stub: no replay for log $arg at $f" >&2
        exit 1 ;;
    esac
  done
  echo "git stub: unsupported git log invocation: $*" >&2
  exit 99
fi
echo "git stub: unsupported invocation: $*" >&2
exit 99
STUB
chmod +x "$HOME/.local/bin/git"

export PATH="$HOME/.local/bin:$PATH"

# --- Fixture layout ---------------------------------------------------------
# Copy the on-disk fixture tree into a writable tmp dir so the test never
# mutates the repo's pristine fixtures. Per LESSONS 2026-05-27 we use `cp`.
PROJECTS="$TMP/projects"
mkdir -p "$PROJECTS"
cp -R "$FIXTURES/projects/agent-fleet" "$PROJECTS/agent-fleet"
export FLEET_DISCOVERY_ROOT="$PROJECTS"

# Seed the per-slug cache (events.jsonl + runs.jsonl) under $HOME/.cache.
CACHE="$HOME/.cache/agent-fleet-agent"
mkdir -p "$CACHE"
cp "$FIXTURES/cache/agent-fleet-agent/events.jsonl" "$CACHE/events.jsonl"
cp "$FIXTURES/cache/agent-fleet-agent/runs.jsonl"   "$CACHE/runs.jsonl"

# Point the implementation at the synthetic git replay tree.
export FLEET_GIT_REPLAY_DIR="$FIXTURES/git-replay"

# Point the prompts CHANGELOG walker at the synthetic kit tree so the test
# does not depend on the real prompts/CHANGELOG.md's contents.
export FLEET_KIT_ROOT="$FIXTURES/kit"

# ===========================================================================
# AC#1 — default invocation: --format text, exit 0, byte-matches golden.
# ===========================================================================
OUT="$TMP/text.out"
set +e
"$FLEET" provenance agent-fleet 57 > "$OUT" 2> "$TMP/text.err"
EXIT=$?
set -e
if [ "$EXIT" != "0" ]; then
  echo "FAIL: AC#1 default text invocation should exit 0, got $EXIT"
  cat "$TMP/text.err"; cat "$OUT"; exit 1
fi
if ! diff -u "$GOLDEN_TEXT" "$OUT"; then
  echo "FAIL: AC#1 text output does not byte-match golden"; exit 1
fi
# The first line must be the documented header.
head -1 "$OUT" | grep -qF -- 'Provenance — agent-fleet PR #57' \
  || { echo "FAIL: AC#1 first-line header missing"; head -1 "$OUT"; exit 1; }
# Key order check — the keys must appear in the documented sequence.
KEYS=$(grep -E '^[a-z][^:]*:' "$OUT" | sed -E 's/:.*//')
EXPECTED='shipped
ticket
branch
prompts SHA
prompts version
heal attempts
infra-flake reruns
review verdict
lesson drafts emitted
cross-fleet lessons at PHASE 0
budget block events
spend'
if [ "$KEYS" != "$EXPECTED" ]; then
  echo "FAIL: AC#1 key order wrong"
  echo "want: $EXPECTED"
  echo "got:  $KEYS"
  exit 1
fi
echo "ok AC#1: default text output matches golden + ordered keys"

# ===========================================================================
# AC#2 — --format md: H1 header, ends with <!-- generated by fleet
#        provenance --> marker, byte-matches md golden.
# ===========================================================================
MDOUT="$TMP/md.out"
"$FLEET" provenance agent-fleet 57 --format md > "$MDOUT"
if ! diff -u "$GOLDEN_MD" "$MDOUT"; then
  echo "FAIL: AC#2 md output does not byte-match golden"; exit 1
fi
head -1 "$MDOUT" | grep -qF -- '# Provenance — agent-fleet PR #57' \
  || { echo "FAIL: AC#2 H1 header missing"; head -1 "$MDOUT"; exit 1; }
grep -qF -- '<!-- generated by fleet provenance -->' "$MDOUT" \
  || { echo "FAIL: AC#2 regenerate marker missing"; cat "$MDOUT"; exit 1; }
echo "ok AC#2: md output matches golden + H1 + marker"

# ===========================================================================
# AC#3 — --format json: one parseable JSON object with the documented
#        snake_cased keys.
# ===========================================================================
JSONOUT="$TMP/json.out"
"$FLEET" provenance agent-fleet 57 --format json > "$JSONOUT"
if ! diff -u "$GOLDEN_JSON" "$JSONOUT"; then
  echo "FAIL: AC#3 json output does not byte-match golden"; exit 1
fi
# Parseability: node -e .
if ! node -e 'JSON.parse(require("fs").readFileSync(0,"utf8"))' < "$JSONOUT" 2>"$TMP/json.parse.err"; then
  echo "FAIL: AC#3 json output does not parse"
  cat "$TMP/json.parse.err"; cat "$JSONOUT"; exit 1
fi
# Documented key set.
for k in shipped_at ticket_id ticket_title branch prompts_sha \
         prompts_changelog_entry heal_attempts infra_flake_reruns \
         review_verdict lesson_drafts_emitted cross_lessons_count \
         cross_lessons_sha budget_block_events spend_usd ; do
  if ! grep -qF -- "\"$k\":" "$JSONOUT"; then
    echo "FAIL: AC#3 json missing key $k"; cat "$JSONOUT"; exit 1
  fi
done
echo "ok AC#3: json parses + documented keys present"

# ===========================================================================
# AC#4 — prompts SHA resolution.
#   PR #57 has a prompts_drift event before pr_opened → drift's `actual`
#   wins (deadbeef…). PR #51 has none → manifest's PROMPTS_SHA wins
#   (7a3e1c0…, read via `git show <merge>:agents.config.sh`).
# ===========================================================================
grep -qF -- 'deadbeef' "$OUT" \
  || { echo "FAIL: AC#4 drift SHA (deadbeef) not in text output"; cat "$OUT"; exit 1; }

CLEAN_OUT="$TMP/clean.text.out"
"$FLEET" provenance agent-fleet 51 > "$CLEAN_OUT"
grep -qF -- '7a3e1c0f' "$CLEAN_OUT" \
  || { echo "FAIL: AC#4 manifest SHA (7a3e1c0f) not in clean PR text output"; cat "$CLEAN_OUT"; exit 1; }
# And the clean PR must NOT advertise drift.
if grep -qF -- 'deadbeef' "$CLEAN_OUT"; then
  echo "FAIL: AC#4 clean PR leaked drift SHA"; cat "$CLEAN_OUT"; exit 1
fi
echo "ok AC#4: drift-wins and manifest-wins branches"

# ===========================================================================
# AC#5 — prompts version: CHANGELOG entry whose date precedes merge ts.
#   PR #57 merged 2026-05-31 → "2026-05-31 — drift handling clarifications".
#   PR #51 merged 2026-05-30 → "2026-05-29 — review send-backs…".
# ===========================================================================
grep -qF -- '2026-05-31' "$OUT" \
  || { echo "FAIL: AC#5 PR #57 expected '2026-05-31' changelog date"; cat "$OUT"; exit 1; }
grep -qF -- '2026-05-29' "$CLEAN_OUT" \
  || { echo "FAIL: AC#5 PR #51 expected '2026-05-29' changelog date"; cat "$CLEAN_OUT"; exit 1; }

# No-changelog branch: point at a kit with an empty CHANGELOG dir.
EMPTY_KIT="$TMP/empty-kit"
mkdir -p "$EMPTY_KIT/prompts"
: > "$EMPTY_KIT/prompts/CHANGELOG.md"
FLEET_KIT_ROOT="$EMPTY_KIT" "$FLEET" provenance agent-fleet 57 > "$TMP/empty-chg.out"
grep -qF -- '(no changelog entry — pre-CHANGELOG ship)' "$TMP/empty-chg.out" \
  || { echo "FAIL: AC#5 empty-changelog branch missing documented fallback"; cat "$TMP/empty-chg.out"; exit 1; }
echo "ok AC#5: changelog-entry resolution (found + no-entry branches)"

# ===========================================================================
# AC#6 — heal attempts: count of `^heal:` subjects in the merge SHA's
#        branch range. Capped at 2.
#   PR #57 fixture has 1 heal commit. PR #51 has 0.
# ===========================================================================
grep -qE '^heal attempts:[[:space:]]+1$' "$OUT" \
  || { echo "FAIL: AC#6 PR #57 should report 1 heal attempt"; cat "$OUT"; exit 1; }
grep -qE '^heal attempts:[[:space:]]+0$' "$CLEAN_OUT" \
  || { echo "FAIL: AC#6 PR #51 should report 0 heal attempts"; cat "$CLEAN_OUT"; exit 1; }

# Cap-at-2 branch: seed a synthetic merge SHA whose subjects file has 3
# `heal:` lines. The renderer must report 2.
CAPLOG="$FIXTURES/git-replay/log/capabc12.subjects.txt"
# Sub-shell write so we don't have to mutate the checked-in fixture dir.
CAPDIR="$TMP/cap-replay"
mkdir -p "$CAPDIR/log" "$CAPDIR/show"
cp -R "$FIXTURES/git-replay/show/." "$CAPDIR/show/"
cp -R "$FIXTURES/git-replay/log/."  "$CAPDIR/log/"
cp "$FIXTURES/git-replay/cross-lessons-sha.txt" "$CAPDIR/cross-lessons-sha.txt"
{
  echo "feat: a thing"
  echo "heal: first"
  echo "heal: second"
  echo "heal: third"
} > "$CAPDIR/log/capabc12.subjects.txt"
# Synthetic manifest for the cap branch (uses the same PROMPTS_SHA).
cp "$FIXTURES/git-replay/show/a1b2c3d4--agents.config.sh" "$CAPDIR/show/capabc12--agents.config.sh"

# Synthetic events for an additional PR #61 → merge_sha=capabc12.
CAP_CACHE="$TMP/cap-cache/agent-fleet-agent"
mkdir -p "$CAP_CACHE"
{
  cat "$FIXTURES/cache/agent-fleet-agent/events.jsonl"
  printf '%s\n' '{"ts":"2026-06-02T09:00:00Z","slug":"agent-fleet","phase":"ship","type":"pr_opened","number":"61","branch":"feat/0030-cap-heal"}'
  printf '%s\n' '{"ts":"2026-06-02T10:00:00Z","slug":"agent-fleet","phase":"ship","type":"run_completed","exit":"0","pr":"61","merge_sha":"capabc12"}'
} > "$CAP_CACHE/events.jsonl"
cp "$FIXTURES/cache/agent-fleet-agent/runs.jsonl" "$CAP_CACHE/runs.jsonl"

CAP_OUT="$TMP/cap.out"
HOME_CAP="$TMP/home-cap"
mkdir -p "$HOME_CAP/.cache" "$HOME_CAP/.local/bin"
cp "$HOME/.local/bin/gh" "$HOME_CAP/.local/bin/gh"
cp "$HOME/.local/bin/git" "$HOME_CAP/.local/bin/git"
cp -R "$TMP/cap-cache/agent-fleet-agent" "$HOME_CAP/.cache/agent-fleet-agent"
HOME="$HOME_CAP" PATH="$HOME_CAP/.local/bin:$PATH" \
  FLEET_GIT_REPLAY_DIR="$CAPDIR" \
  FLEET_KIT_ROOT="$FIXTURES/kit" \
  FLEET_DISCOVERY_ROOT="$PROJECTS" \
  "$FLEET" provenance agent-fleet 61 > "$CAP_OUT"
grep -qE '^heal attempts:[[:space:]]+2$' "$CAP_OUT" \
  || { echo "FAIL: AC#6 cap-at-2 not enforced"; cat "$CAP_OUT"; exit 1; }
echo "ok AC#6: heal-attempts (0/1/2-capped) branches"

# ===========================================================================
# AC#7 — infra-flake reruns: count + pattern listed parenthetically.
#   PR #57 has 1 (gh_graphql_502); PR #51 has 0.
# ===========================================================================
grep -qE '^infra-flake reruns:[[:space:]]+1 \(gh_graphql_502' "$OUT" \
  || { echo "FAIL: AC#7 PR #57 should report 1 (gh_graphql_502) rerun"; cat "$OUT"; exit 1; }
grep -qE '^infra-flake reruns:[[:space:]]+0$' "$CLEAN_OUT" \
  || { echo "FAIL: AC#7 PR #51 should report 0 infra-flake reruns"; cat "$CLEAN_OUT"; exit 1; }
echo "ok AC#7: infra-flake reruns (zero + one + pattern) branches"

# ===========================================================================
# AC#8 — review verdict: --request-changes when lesson_draft_emitted fired
#        for this PR; --comment otherwise. No `gh api`.
# ===========================================================================
grep -qE '^review verdict:[[:space:]]+--request-changes' "$OUT" \
  || { echo "FAIL: AC#8 PR #57 expected --request-changes verdict"; cat "$OUT"; exit 1; }
grep -qE '^review verdict:[[:space:]]+--comment' "$CLEAN_OUT" \
  || { echo "FAIL: AC#8 PR #51 expected --comment verdict"; cat "$CLEAN_OUT"; exit 1; }
echo "ok AC#8: review verdict (request-changes + comment) branches"

# ===========================================================================
# AC#9 — cross-fleet lessons at PHASE 0: count of `^### ` lines in
#        CROSS_LESSONS.md at the merge ts.
# ===========================================================================
grep -qE '^cross-fleet lessons at PHASE 0:[[:space:]]+14 \(sha c0ffee01' "$OUT" \
  || { echo "FAIL: AC#9 expected '14 (sha c0ffee01)' cross-lessons count"; cat "$OUT"; exit 1; }

# Fallback branch: no replay dir → current file's count from kit root.
mkdir -p "$EMPTY_KIT"
cat > "$EMPTY_KIT/CROSS_LESSONS.md" <<'EOF'
# CROSS_LESSONS
## agent-fleet
### only-one entry
EOF
FLEET_KIT_ROOT="$EMPTY_KIT" FLEET_GIT_REPLAY_DIR= \
  "$FLEET" provenance agent-fleet 57 > "$TMP/fallback.out" 2>"$TMP/fallback.err" || true
grep -qE '^cross-fleet lessons at PHASE 0:[[:space:]]+1' "$TMP/fallback.out" \
  || { echo "FAIL: AC#9 fallback branch should count from kit's current file"; cat "$TMP/fallback.out"; cat "$TMP/fallback.err"; exit 1; }
echo "ok AC#9: cross-fleet lessons count (replay + fallback) branches"

# ===========================================================================
# AC#10 — spend: digest_spend_since restricted to [pr_opened.ts, merged.ts].
# ===========================================================================
grep -qE '^spend:[[:space:]]+\$0\.92$' "$OUT" \
  || { echo "FAIL: AC#10 PR #57 expected spend \$0.92"; cat "$OUT"; exit 1; }
grep -qE '^spend:[[:space:]]+\$0\.46$' "$CLEAN_OUT" \
  || { echo "FAIL: AC#10 PR #51 expected spend \$0.46"; cat "$CLEAN_OUT"; exit 1; }
echo "ok AC#10: spend window correct for both PRs"

# ===========================================================================
# AC#11 — unknown PR → stderr documented error, exit 2.
# ===========================================================================
set +e
"$FLEET" provenance agent-fleet 999 > "$TMP/unknown-pr.out" 2> "$TMP/unknown-pr.err"
EX=$?
set -e
if [ "$EX" != "2" ]; then
  echo "FAIL: AC#11 unknown PR should exit 2, got $EX"
  cat "$TMP/unknown-pr.err"; exit 1
fi
EXP_PR_ERR='provenance: PR #999 not found in events.jsonl for agent-fleet (no pr_opened or run_completed event matched)'
if ! grep -qF -- "$EXP_PR_ERR" "$TMP/unknown-pr.err"; then
  echo "FAIL: AC#11 unknown-PR stderr does not contain documented error"
  echo "want: $EXP_PR_ERR"
  cat "$TMP/unknown-pr.err"; exit 1
fi
echo "ok AC#11: unknown PR documented error + exit 2"

# ===========================================================================
# AC#12 — unknown slug → stderr documented error, exit 2.
# ===========================================================================
set +e
"$FLEET" provenance not-a-real-slug 1 > "$TMP/unknown-slug.out" 2> "$TMP/unknown-slug.err"
EX=$?
set -e
if [ "$EX" != "2" ]; then
  echo "FAIL: AC#12 unknown slug should exit 2, got $EX"
  cat "$TMP/unknown-slug.err"; exit 1
fi
EXP_SLUG_ERR="provenance: no project with SLUG=not-a-real-slug found (looked under FLEET_DISCOVERY_ROOT=$PROJECTS)"
if ! grep -qF -- "$EXP_SLUG_ERR" "$TMP/unknown-slug.err"; then
  echo "FAIL: AC#12 unknown-slug stderr does not contain documented error"
  echo "want: $EXP_SLUG_ERR"
  cat "$TMP/unknown-slug.err"; exit 1
fi
echo "ok AC#12: unknown slug documented error + exit 2"

# ===========================================================================
# AC#13 — --help banner mentions --format, --help, three format values
#        (text/md/json), and one example. Assertion uses grep -qF -- per
#        LESSONS 2026-05-30 (end-of-options before a leading-dash pattern).
#        The function MUST end with `exit 0` per LESSONS 2026-06-01 — the
#        cheapest check is: invoking `--help` must produce ONLY the help
#        banner, not the help banner followed by `fleet status` content.
# ===========================================================================
HOUT="$TMP/help.out"
"$FLEET" provenance --help > "$HOUT" 2>&1
for kw in '--format' '--help' 'text' 'md' 'json' 'fleet provenance'; do
  if ! grep -qF -- "$kw" "$HOUT"; then
    echo "FAIL: AC#13 help banner missing '$kw'"
    cat "$HOUT"; exit 1
  fi
done
# Dispatcher fall-through trap: status table header must NOT appear.
if grep -qE '^PROJECT[[:space:]]+INSTALLED' "$HOUT"; then
  echo "FAIL: AC#13 help printed the default fleet status table — function missing 'exit 0'"
  cat "$HOUT"; exit 1
fi
echo "ok AC#13: help banner + no dispatcher fall-through"

echo
echo "ALL provenance tests passed"
